name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Compile sources
        run: python -m compileall Toolchain

      - name: Static check (ruff - optional)
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          ruff check Toolchain || true

